# Build configuration using opensuse leap as the base image

ProjectName: "etcd-setup"
BaseImage: "registry.opensuse.org/opensuse/leap:16.0"
Distro: "suse"

Buildah:
  Path: "buildah"

Etcd:
  Version: "3.5.11"
  SourceUrl: "https://github.com/etcd-io/etcd/releases/download/v3.5.11/etcd-v3.5.11-linux-amd64.tar.gz"
  Prefix: "/usr/local/etcd"
  Build:
    Dependencies: [
      "tar", "curl", "gzip"
    ]
  Runtime:
    Dependencies: [
      "shadow",
      "hostname",
      "timezone",
      "ca-certificates",
      "ca-certificates-mozilla"
    ]
    RemoveDependencies: []
    Environment:
      - "TZ=Africa/Nairobi"
      - "LANG=C.UTF-8"
    Resources: "resources"
    DataDir: "/usr/local/etcd/data"
    Uid: 1001 # user id
    Gid: 1001 # group id
    Ports:
      - 2379 # Client
      - 2380 # Peer

